[workspace]
members = [
    # "node",
    # "runtime/stout",
    # "runtime/trappist",
    "pallets/asset-registry",
    "primitives/xcm",
]
exclude = ["contracts", "xcm-simulator"]

[profile.release]
panic = "unwind"
